# Defines the services and databases for the EverShop application on Render.
# See https://render.com/docs/blueprint-spec for a full reference.

databases:
  # A free-tier PostgreSQL database for our EverShop application.
  - name: evershop-database
    plan: free # Use Render's free plan for PostgreSQL

services:
  # The EverShop application itself, running as a web service.
  - type: web
    name: evershop-app
    plan: free # Use Render's free plan for web services
    runtime: docker # Specify the runtime as Docker
    # Tell Render to use the pre-built Docker image from Docker Hub.
    image:
      url: evershop/evershop:latest
    # Set the environment variables to connect to our new database.
    # Render automatically provides the connection details using 'fromDatabase'.
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: evershop-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: evershop-database
          property: port
      - key: DB_USER
        fromDatabase:
          name: evershop-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: evershop-database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: evershop-database
          property: database
      - key: NODE_ENV
        value: production
