# Defines the services and databases for the EverShop application on Render.
# See https://render.com/docs/blueprint-spec for full reference.

# Use your existing Render PostgreSQL database
# Replace DATABASE_NAME with your actual database name from Render dashboard
databases:
  - name: DATABASE_NAME
    plan: free

services:
  # The EverShop application itself, running as a web service.
  - type: web
    name: evershop-app
    plan: free # Using free plan
    runtime: image
    image:
      url: evershop/evershop:latest
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: evershop-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: evershop-database
          property: port
      - key: DB_USER
        fromDatabase:
          name: evershop-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: evershop-database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: evershop-database
          property: database
      - key: NODE_ENV
        value: production
      - key: ADMIN_EMAIL
        value: admin@evershop.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: SESSION_SECRET
        value: your_session_secret_here
      - key: CSRF_SECRET
        value: your_csrf_secret_here


