# Defines the services and databases for the EverShop application on Render.
# See https://render.com/docs/blueprint-spec for full reference.

databases:
  # A free-tier PostgreSQL database for our EverShop application.
  - name: evershop-database
    plan: free

services:
  # The EverShop application itself, running as a web service.
  - type: web
    name: evershop-app
    plan: free
    runtime: image                    # Pull a prebuilt image
    image:
      url: evershop/evershop:latest   # Your Docker Hub image
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: evershop-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: evershop-database
          property: port
      - key: DB_USER
        fromDatabase:
          name: evershop-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: evershop-database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: evershop-database
          property: database      # use the valid 'database' property
      - key: NODE_ENV
        value: production
