  - type: cron
    name: create-admin-user
    plan: starter                   # “free” isn’t valid for cron jobs—use starter or above
    runtime: image
    schedule: "0 5 31 2 0"         # never runs automatically
    image:
      url: evershop/evershop:latest
    dockerCommand: npm run user:create -- --email "khoualdiyassin26@gmail.com" --password "test123" --name "yassin"
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: evershop-database
          property: host
      - key: DB_PORT
        fromDatabase:
          name: evershop-database
          property: port
      - key: DB_USER
        fromDatabase:
          name: evershop-database
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: evershop-database
          property: password
      - key: DB_NAME
        fromDatabase:
          name: evershop-database
          property: database
      - key: NODE_ENV
        value: production
